---
ssh: ascross

package: radarr
name: Radarr
version: 0.2.0.778
architecture:
firmware: 2.6.0

config:
  general:
    developer: "Radarr"
    website: "https://github.com/Radarr/Radarr"
    maintainer: "mafredri"
    email: "mafredri+adm@gmail.com"
    depends:
      - mono
    package: "PACKAGE"
    name: "NAME"
    version: "VERSION"
    architecture: "ARCHITECTURE"
    firmware: "FIRMWARE"
  adm-desktop:
    app:
      port: 7878
      protocol: http
      type: custom
      url: /
    privilege:
      accessible: users
      customizable: true
  register:
    boot-priority:
      start-order: 60
      stop-order: 60
    port:
      - 7878

case_sensitive: false
runpath: /usr/local/AppCentral/radarr/lib
root: /usr
files:
  - /usr/bin/sqlite3
  - /usr/lib/libtinyxml2.so*
  - /usr/lib/libzen.so*
  - /usr/lib/libmediainfo.so*
  - /usr/lib/libsqlite3.so*
